server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.233.133:8848    # ← 加这里

  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:127.0.0.1}:3306/ticket_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  ai:
    openai:
      api-key: sk-ws-H.PIIEPIR.mHeL.MEQCIECvIpbOveKtoscbaMYD_Z13s0X894ERLdu-JgLCSEIlAiB_mSLiKZwE_QQbY6NhTYHWSXOTkGEJXRB7klRDeBjjwQ
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v4

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto